// This file is automatically generated. Do not modify it manually.
// For more information, see the Firebase CLI documentation:
// https://firebase.google.com/docs/cli/

export const firebaseConfig = {
  projectId: "studio-1115246596-9066a",
  appId: "1:824116582624:web:8dddf0bd87a64c111f1885",
  storageBucket: "studio-1115246596-9066a.appspot.com",
  apiKey: "AIzaSyDOyDPiXWvyfd48NvkcWHYI8sf8taWy9CI",
  authDomain: "studio-1115246596-9066a.firebaseapp.com",
  messagingSenderId: "824116582624",
};