// This file is automatically generated. Do not modify.
// Instead, copy this file to firebase.config.ts and update the values there.

// This is the configuration for the Firebase project.
// It is used to initialize the Firebase app.

export const firebaseConfig = {
  apiKey: "AIzaSyDOyDPiXWvyfd48NvkcWHYI8sf8taWy9CI",
  authDomain: "studio-1115246596-9066a.firebaseapp.com",
  projectId: "studio-1115246596-9066a",
  storageBucket: "studio-1115246596-9066a.appspot.com",
  messagingSenderId: "824116582624",
  appId: "1:824116582624:web:8dddf0bd87a64c111f1885"
};
